### ISSUE TITLE
Gate fusion yields no speedup

### ISSUE THREAD

**Issue by jandrovins** [intel/intel-qs#51]
Hello!

I am trying to replicate the ~2.5x speedup of gate fusion showed in the paper of qHipster. I have tried using hadamard gates on a Quantum register of 30 qubits, when log2llc=20 and fusing from 2 gates to 20 gates. No speedup.

Am i doing something wrong? Could you explain a configuration that replicates the ~2.5 speedup?

**Comment by giangiac** [comment]
Hi @jandrovins,

Are you referring to the gate fusion from the 2016 preprint or the compilation optimization from the 2020 preprint?

Gian

**Comment by ghost** [comment]
Hello! Just to clarify, "gate fusion" does not mean what it might sound like to a quantum person--it's not a fusion of many single-qubit gates. It's a term in computer science unrelated to quantum. It's not clear to me that your particular example (many hadamard gates in a row) is an example that takes much advantage of this feature.

(I believe the original 2.5x speedup was specifically for QFT)

If you want to multiply many 1q gates together before operating on the state vector, then I believe you would need to perform those small multiplications before you feed into qhipster. qhipster was originally supposed to be primarily a library of low-level functions, though Intel has been adding more mid- and high-level features since that first publications.

Apologies if I misunderstood the question.

-N
